ATMEL: nf_drv.c File Reference
nf_drv.c File Reference
#include "config.h"
#include "conf_nf.h"
#include "nf.h"
#include "nf_drv.h"
Defines
#define _nfc_drv_c_
#define NF_XMCR_MODULE_SHARED DISABLED
#define BAD_BLOCK_OFFSET 0
Functions
__no_init volatile
xdata Byte
nf_send_cmd At (0x3900)
__no_init volatile
xdata Byte
nf_send_add At (0x3A00)
__no_init volatile
xdata Byte nf_data At (0x3800)
void nfc_select_dev (U8 dev)
U8 nfc_check_type (U8 nb_dev)
Tests the Nand Flash configuration.
void nfc_reset_nands (U8 nb_dev)
Reset all the NF devices.
void nf_XMCR_enable (void)
Enable the XMCR (Extending Memory Module) of the AVR to drive the NAND Flash.
void nf_XMCR_disable (void)
Disable the XMCR module of the AVR, to allow access to others peripherals that may be connected on this same bus.
Status_bool nfc_check_status (void)
Check the status of the selected device.
void nfc_open_page_read (U32 page_addr, U16 byte_addr)
Opens a page for read.
void nfc_open_page_write (U32 page_addr, U16 byte_addr)
Opens a page for write.
void nfc_mark_bad_block (U32 page_addr)
Mark a block as 'invalid' by clearing it entirely.
void nfc_erase_block (U32 page_addr, U8 force_erase)
Erases a block.
void nfc_read_spare_byte (U8 _MEM_TYPE_SLOW_ *p_byte, U8 n_byte, U32 page_addr)
Reads the number spare bytes specified and stores them in a array.
void nfc_wait_busy (void)
Tests the true busy.
U32 nfc_read_id (U8 read_id_cmd, U8 nf_num)
Read the ID of the Nand-Flash.
static Bool nfc_nf_is_ready (void)
Check the status Ready/Busy of the Nand Flash.
U8 nfc_detect (void)
Read the ID of the Nand-Flash and update the global variable.
void nfc_copy_back_init (U32 page_addr)
Prepare a copy-back session.
Variables
U16 bad_block_table [100]
Detailed Description
This file contains the low level functions for the Nand-Flash Controller.
Compiler: IAR EWAVR and GNU GCC for AVR
Supported devices: AT90USB1287, AT90USB1286, AT90USB647, AT90USB646
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file nf_drv.c.
Define Documentation
#define _nfc_drv_c_
Definition at line 46 of file nf_drv.c.
#define NF_XMCR_MODULE_SHARED DISABLED
Definition at line 68 of file nf_drv.c.
#define BAD_BLOCK_OFFSET 0
Definition at line 71 of file nf_drv.c.
Function Documentation
__no_init volatile xdata Byte nf_send_cmd At (0x3900)
__no_init volatile xdata Byte nf_send_add At (0x3A00)
__no_init volatile xdata Byte nf_data At (0x3800)
void nfc_select_dev (U8 dev)
Definition at line 83 of file nf_drv.c.
{
   if(0==dev)
   {
      Nandflash1_unselect();
      Nandflash0_select();
   }else{
      Nandflash0_unselect();
      Nandflash1_select();
   }
}
U8 nfc_check_type (U8 nb_dev)
Tests the Nand Flash configuration.
The function verifies that the NF connected to device are properly declared in conf_nf.h.
Parameters:
none
Returns:
The number of device connected and corresponding to NF identifiers.
Definition at line 107 of file nf_drv.c.
Referenced by main().
{
   U8 i_dev;
   if( 2 < nb_dev )
      nb_dev = 2; // Only 1 or 2 for this driver
#if (NF_XMCR_MODULE_SHARED == ENABLED)
   nf_XMCR_enable();
#endif
   nfc_init(        nb_dev, 0 );
   nfc_reset_nands( nb_dev ); // Reset all the NF devices
   // Test NF configuration
   //
   for( i_dev=0 ; i_dev<nb_dev ; i_dev++ )
   {
      Nfc_action( NFC_ACT_DEV_SELECT, i_dev);
      nfc_wait_busy();
      Nfc_action( NFC_ACT_ASSERT_CE, NFC_EXT_CELOW);
      Nfc_set_cmd(NF_READ_ID_CMD);
      Nfc_set_adc( 0 );
      if(( Nfc_rd_data_fetch_next()!=G_DEV_MAKER  )
      || ( Nfc_rd_data_fetch_next()!=G_DEV_ID     ))
      {
         return i_dev;
      }
      if( G_CE_TOGGLE )
      {
         // disable CE Low
         Nfc_action( NFC_ACT_ASSERT_CE, NFC_EXT_NOP);
      }
   }
#if (NF_XMCR_MODULE_SHARED == ENABLED)
   nf_XMCR_disable();
#endif
   return nb_dev;
}
void nfc_reset_nands (U8 nb_dev)
Reset all the NF devices.
Parameters:
none
Definition at line 152 of file nf_drv.c.
Referenced by nf_dfc_write_stop(), nfc_check_type(), and nfc_detect().
{
   U8 i_dev;
   Mcu_set_sfr_page_nfc();
   for( i_dev=0 ; i_dev<nb_dev ; i_dev++ )
   {
      Nfc_action(NFC_ACT_DEV_SELECT, i_dev);
      // The wait is mandatory here since the function is used to wait any
      // pending internal programmation (Cache Program cmd).
      nfc_wait_busy();
      Nfc_set_cmd(NF_RESET_CMD);
      nfc_wait_busy();
   }
}
void nf_XMCR_enable (void)
Enable the XMCR (Extending Memory Module) of the AVR to drive the NAND Flash.
Definition at line 172 of file nf_drv.c.
Referenced by nf_nf_2_ram(), nf_ram_2_nf(), nf_read_10(), nf_read_capacity(), nf_test_unit_ready(), nf_usb_stop(), nf_write_10(), nfc_check_type(), and nfc_detect().
{
#if (NF_CLE_ALE_MANUAL == ENABLED)
  XMCRB |= ((1<<XMM2) | (1<<XMM1) | (1<<XMM0));   // limit XRAM interface to A7 (release PC0..7)
#else
  XMCRB |= ((1<<XMM2) | (1<<XMM1));                // limit XRAM interface to A9 (release PC2..7)
#endif
  XMCRA |= (1<<SRE);                  // enable the external memory
}
void nf_XMCR_disable (void)
Disable the XMCR module of the AVR, to allow access to others peripherals that may be connected on this same bus.
Definition at line 185 of file nf_drv.c.
Referenced by nf_nf_2_ram(), nf_ram_2_nf(), nf_read_10(), nf_read_capacity(), nf_test_unit_ready(), nf_usb_stop(), nf_write_10(), nfc_check_type(), and nfc_detect().
{
  Nandflash0_unselect();
  Nandflash1_unselect();
  XMCRA &= ~(1<<SRE);  // disable the external memory
}
Status_bool nfc_check_status (void)
Check the status of the selected device.
Returns:
a status: PASS if the status is PASS; FAIL if the status is FAIL
Definition at line 203 of file nf_drv.c.
Referenced by nf_cleanup_memory(), nf_write_fbb(), and nf_write_lut().
{
   Mcu_set_sfr_page_nfc();
   nfc_wait_busy(); // Send a status command and wait the completion of the last command
   if ( (Nfc_rd_data()&NF_MASK_STATUS_FAIL)==0 ) { return PASS; } // I/O 0   Pass:0  Fail:1
   else                                          { return FAIL; }
}
void nfc_open_page_read (U32 page_addr, U16 byte_addr)
Opens a page for read.
The function will adapt the commands according to the type of flash memory. The busy is polled at the end of the function.
Parameters:
page_addr absolute page address of the block
byte_addr relative byte address inside the page.
Precondition:
nf_init() should have been called before. The NF device should have been selected before with Nfc_action(NFC_ACT_DEV_SELECT, id).
Definition at line 221 of file nf_drv.c.
Referenced by nf_cache_fbb_flush(), nf_cache_fbb_refill(), nf_cache_lut_flush(), nf_cache_lut_refill(), nf_check_fbb(), nf_check_lut(), nf_cleanup_memory(), nf_copy(), nf_copy_tail(), nf_nf_2_ram(), nf_open_write(), nf_read_10(), nf_rebuild(), nf_refine_index(), nfc_erase_block(), and nfc_read_spare_byte().
{
   Mcu_set_sfr_page_nfc();
   nfc_wait_busy();
   Nfc_open_page_read( page_addr, byte_addr);
}
void nfc_open_page_write (U32 page_addr, U16 byte_addr)
Opens a page for write.
The function will adapt the commands according to the type of flash memory.
Parameters:
page_addr absolute page address of the block
byte_addr relative byte address inside the page.
Precondition:
nf_init() should have been called before. The NF device should have been selected before with Nfc_action(NFC_ACT_DEV_SELECT, id).
Definition at line 239 of file nf_drv.c.
Referenced by nf_copy(), nf_copy_tail(), nf_open_write(), nf_ram_2_nf(), nf_write_10(), nf_write_fbb(), nf_write_lut(), and nfc_mark_bad_block().
{
   Mcu_set_sfr_page_nfc();
   Nfc_open_page_write( page_addr, byte_addr);
}
void nfc_mark_bad_block (U32 page_addr)
Mark a block as 'invalid' by clearing it entirely.
Parameters:
page_addr absolute page address of the block
Precondition:
nf_init() should have been called before. The device which holds this bad block should have been selected before with Nfc_action(NFC_ACT_DEV_SELECT, id).
Definition at line 255 of file nf_drv.c.
Referenced by nf_cleanup_memory(), and nf_rebuild().
{
   U8  n_bytes;
   U8  i_byte;
   U8  i_page;
   Mcu_set_sfr_page_nfc();
   n_bytes= ( Is_nf_512() )
   ?  16  // 512B page access
   :  64  // 2KB  page access
   ;
   // Erasing the block is mandatory to prevent partial programming
   // (some 512B NF does support partial prog, but not after a copy back command).
   nfc_erase_block( page_addr, TRUE );
   for ( i_page=(U8)1<<G_SHIFT_BLOCK_PAGE ; i_page!=0 ; i_page--, page_addr++ )
   {
      nfc_open_page_write( page_addr, NF_SPARE_POS-8 );
      Nfc_wr_data('A'); Nfc_wr_data('t');
      Nfc_wr_data('m'); Nfc_wr_data('e');
      Nfc_wr_data('l'); Nfc_wr_data(' ');
      Nfc_wr_data(' '); Nfc_wr_data(' ');
      for ( i_byte=n_bytes ; i_byte!=0 ; i_byte-=4 )
      {
         Nfc_wr_data(0);
         Nfc_wr_data(0);
         Nfc_wr_data(0);
         Nfc_wr_data(0);
      }
      Nfc_set_cmd(NF_PAGE_PROGRAM_CMD); // Confirm programmation
   }
}
void nfc_erase_block (U32 page_addr, U8 force_erase)
Erases a block.
The erase will be done only if the block is not bad
Parameters:
page_addr absolute page address of the block
force_erase TRUE forces erasing, FALSE erases the block (if not bad)
Precondition:
nf_init() should have been called before. The device which holds the block to delete should have been selected before with Nfc_action(NFC_ACT_DEV_SELECT, id).
Definition at line 302 of file nf_drv.c.
Referenced by nf_cache_fbb_flush(), nf_cache_lut_flush(), nf_cleanup_memory(), nf_erase_all_blocks(), nf_erase_old_blocks(), nf_fetch_free_block(), nf_rebuild(), nfc_mark_bad_block(), and ut_nfc_erase_all().
{
   Mcu_set_sfr_page_nfc();
   if (FALSE == force_erase)
   {
      nfc_open_page_read( page_addr, NF_SPARE_POS + G_OFST_BLK_STATUS );
      if( (Nfc_rd_data() != 0xFF) ) return;    // The block is bad. We can not erase it
   }
   nfc_wait_busy();
   Nfc_unprotect_all_flash();                    // WP may be actif due to block protection
   Nfc_set_cmd (NF_BLOCK_ERASE_CMD);             // Auto Block Erase Setup
   Nfc_set_adr( LSB0(page_addr) );
   Nfc_set_adr( LSB1(page_addr) );
   if (3 == G_N_ROW_CYCLES)
   {
      Nfc_set_adr( MSB1(page_addr) );
   }
   Nfc_set_cmd(NF_BLOCK_ERASE_CONFIRM_CMD);      // Erase command
}
void nfc_read_spare_byte (U8 _MEM_TYPE_SLOW_ * p_byte, U8 n_byte, U32 page_addr)
Reads the number spare bytes specified and stores them in a array.
Parameters:
p_byte pointer on the array in which are stored the spare bytes.
n_byte number of spare bytes to read.
page_addr absolute page address of the block.
Precondition:
nf_init() should have been called before. The NF device should have been selected before with Nfc_action(NFC_ACT_DEV_SELECT, id).
Definition at line 333 of file nf_drv.c.
Referenced by nf_fetch_free_block(), nf_rebuild(), and nf_scan().
{
   U8  i;
   Mcu_set_sfr_page_nfc();
   nfc_open_page_read( page_addr, NF_SPARE_POS);
   for ( i=0 ; i!=n_byte ; i++ )
   {
      p_byte[i] = Nfc_rd_data_fetch_next();
   }
}
void nfc_wait_busy (void)
Tests the true busy.
Note that we test twice the ready, since there is an hardware minimum requirement between the end of the busy and the first read cycle. Since the busy is not wired, the ready is tested twice.
Definition at line 353 of file nf_drv.c.
Referenced by nfc_check_status(), nfc_check_type(), nfc_copy_back_init(), nfc_erase_block(), nfc_open_page_read(), nfc_read_id(), and nfc_reset_nands().
{
   register int Reg;
   Nfc_set_cmd(NF_READ_STATUS_CMD);
   Reg = Nfc_rd_status();
   if( Is_nf_2k() )
   {
      if( G_CACHE_PROG )
      {
         while( (Nfc_rd_status() & NF_MASK_STATUS_T_RDY_2KB )==0 );
         while( (Nfc_rd_status() & NF_MASK_STATUS_T_RDY_2KB )==0 );
      }
      else
      {
         while( (Nfc_rd_status() & NF_MASK_STATUS_READY     )==0 );
         while( (Nfc_rd_status() & NF_MASK_STATUS_READY     )==0 );
      }
   }
   if( Is_nf_512() )
   {
      while( (Nfc_rd_status() & NF_MASK_STATUS_T_RDY_512B )==0 );
      while( (Nfc_rd_status() & NF_MASK_STATUS_T_RDY_512B )==0 );
   }
}
U32 nfc_read_id (U8 read_id_cmd, U8 nf_num)
Read the ID of the Nand-Flash.
Parameters:
read_id_cmd Read_id command (NF_READ_ID_CMD, NF_READ_ID2_CMD)
nf_num Nand Flash number
Returns:
: MSB0(ret) (MSB) is the Maker Code, MSB1(ret) is the Device Id, MSB2(ret) is 3rd byte returned, MSB3(ret) (LSB) is 4th byte returned.
Precondition:
nf_init() should have been called before.
Definition at line 397 of file nf_drv.c.
Referenced by nfc_detect().
{
   U32 ret;
   Mcu_set_sfr_page_nfc();
   Nfc_action(NFC_ACT_DEV_SELECT, nf_num);
   nfc_wait_busy();
   Nfc_action( NFC_ACT_ASSERT_CE, NFC_EXT_CELOW);
   Nfc_set_cmd (read_id_cmd);
   Nfc_set_adc( 0 );
   MSB0(ret)= Nfc_rd_data_fetch_next(); // Maker Code
   MSB1(ret)= Nfc_rd_data_fetch_next(); // Device Id
   MSB2(ret)= Nfc_rd_data_fetch_next(); // extra
   MSB3(ret)= Nfc_rd_data_fetch_next(); // extra (Multi Plane Support)
   Nfc_action( NFC_ACT_ASSERT_CE, NFC_EXT_NOP);
   return ret;
}
static Bool nfc_nf_is_ready (void) [static]
Check the status Ready/Busy of the Nand Flash.
Returns:
Bool TRUE -> The Nand Flash is ready and connected FALSE -> The Nand Flash must be no connected (timeout)
Definition at line 423 of file nf_drv.c.
References FALSE, NF_MASK_STATUS_READY, NF_MAX_RB_TIMEOUT, NF_READ_STATUS_CMD, Nfc_rd_status, Nfc_set_cmd, and TRUE.
Referenced by nfc_detect().
{
   register U8 Reg;
   U8 u8_timeout;
   Nfc_set_cmd( NF_READ_STATUS_CMD );  // send status for each read, because the NF must be in reset sequence
   Reg = Nfc_rd_status();            // active first read
   for (u8_timeout=NF_MAX_RB_TIMEOUT ; u8_timeout!=0 ; u8_timeout--)
   {
      if(( (Nfc_rd_status() & NF_MASK_STATUS_READY) !=0 )    // the busy pin is not tested, and the bit ready may be wrong penddind the rise of busy pin
      && ( (Nfc_rd_status() & NF_MASK_STATUS_READY) !=0 ) )  // To not read a wrong status, we check the status after 6 cycles (300ns)
      {
            return TRUE;  // NF READY
      }
   }
   return FALSE;          // TIMEOUT
}
U8 nfc_detect (void)
Read the ID of the Nand-Flash and update the global variable.
Returns:
: nf index of listing "nf_listing" otherwise : NO_NF_CONNECTED or NF_UNKNOW
Definition at line 449 of file nf_drv.c.
Referenced by main().
{
   U32   u32_nf_ids;
   U8    u8_i, u8_conf;
#if (NF_XMCR_MODULE_SHARED == ENABLED)
   nf_XMCR_enable();
#endif
   // Init the Nand Flash Controller
   nfc_init(        NF_MAX_DEVICES, 0 );
   nfc_reset_nands( NF_MAX_DEVICES ); // Reset all the NF devices
   // Check the presence of device 0
   if ( FALSE == nfc_nf_is_ready() )
   {
      #if (NF_XMCR_MODULE_SHARED == ENABLED)
         nf_XMCR_disable();
      #endif
      return NO_NF_CONNECTED;
   }
   // Read the Nand Flash IDs of device 0
   u32_nf_ids = nfc_read_id( NF_READ_ID_CMD, 0 );
   // Identify the Nand Flash (device 0)
   for( u8_i=0 ; u8_i < (sizeof(nf_list_id)/sizeof(St_nf_id)) ; u8_i++)
   {
      if((nf_list_id[u8_i].manuf == MSB0(u32_nf_ids))
      && (nf_list_id[u8_i].dev   == MSB1(u32_nf_ids)))
         break; // here, ID is know
   }
   if( u8_i == (sizeof(nf_list_id)/sizeof(St_nf_id)) )
   {
      #if (NF_XMCR_MODULE_SHARED == ENABLED)
         nf_XMCR_disable();
      #endif
      return NF_UNKNOW;
   }
   // Set NF configuration parameters for initialisation and access
#if (NF_GENERIC_DRIVER==TRUE)
#  error Test me...
   g_shift_page_byte    =;
   g_shift_block_page   =;
#endif
#if (NF_GENERIC_DRIVER==TRUE) || (NF_AUTO_DETECT_2KB==TRUE) ||(NF_AUTO_DETECT_512B==TRUE)
   // Record info
   u8_conf     =  nf_list_id[u8_i].conf;
   g_dev_maker =  MSB0(u32_nf_ids); // Device maker
   g_dev_id    =  MSB1(u32_nf_ids); // Device ID
   // Search the number of block of device
   for( u8_i=0 ; u8_i < (sizeof(nf_list_link_id_block)/sizeof(St_nf_link_id_block)) ; u8_i++)
   {
      if( nf_list_link_id_block[u8_i].dev_id == g_dev_id )
         break; // ID found
   }
   if( u8_i == (sizeof(nf_list_link_id_block)/sizeof(St_nf_link_id_block)) )
      while(1);   // Error in NF definition
   g_n_zones            =  nf_list_link_id_block[u8_i].nb_zones;
#if (NF_AUTO_DETECT_2KB==TRUE)
   if( 1 == g_n_zones )
      g_n_row_cycles    =  2;
   else
      g_n_row_cycles    =  3;
#endif
#if (NF_AUTO_DETECT_512B==TRUE)
   if( 2 >= g_n_zones )
      g_n_row_cycles    =  2;
   else
      g_n_row_cycles    =  3;
#endif
   g_n_blocks           =  g_n_zones*1024L;
   g_copy_back_cont     = nf_list_conf[u8_conf].copy_back_cont   ;
   g_copy_back_discont  = nf_list_conf[u8_conf].copy_back_discont;
   g_cache_program      = nf_list_conf[u8_conf].cache_program    ;
   g_ce_toggle             = nf_list_conf[u8_conf].ce_toggle;
/*
   g_clock_dfc_nfc      = (nf_list_conf[u8_conf].dfc_nfc_clock<<5) & MSK_DNFCKS;
   Mcu_set_sfr_page_nfc();
   Nfc_set_read_timing((U8)nf_list_conf[u8_conf].timing_read );
   if( !g_ce_toggle )
   {
      // Enable CE low
      Nfc_action( NFC_ACT_ASSERT_CE, NFC_EXT_CELOW);
   }
*/
#endif
#if (NF_XMCR_MODULE_SHARED == ENABLED)
   nf_XMCR_disable();
#endif
   return u8_i;
}
void nfc_copy_back_init (U32 page_addr)
Prepare a copy-back session.
Parameters:
page_addr absolute source page address of the block
Precondition:
nf_init() should have been called before.
Definition at line 558 of file nf_drv.c.
Referenced by nf_copy().
{
   Mcu_set_sfr_page_nfc();
   nfc_wait_busy();
   Nfc_unprotect_all_flash(); // WP may be actif due to block protection
   Nfc_set_cmd(NF_READ_CMD);
   Nfc_set_adc( 0 );
   Nfc_set_adc( 0 );
   Nfc_set_adr( LSB0(page_addr) );
   Nfc_set_adr( LSB1(page_addr) );
   if ( 3==G_N_ROW_CYCLES )
   {
      Nfc_set_adr( MSB1(page_addr) );
   }
   Nfc_set_cmd(NF_COPY_BACK_CMD);
   nfc_wait_busy();
}
Variable Documentation
U16 bad_block_table[100]