ATMEL: debug.c File Reference
debug.c File Reference
#include "config.h"
#include "debug.h"
Defines
#define _TRACE_ (DISABLE)
Functions
void trace_u32 (U32 val)
Fonction used to display a byte value in the decimal form (16 bits) on OCD/Serial Debug Interface.
void trace_u16 (U16 val)
Fonction used to display a 16-bit value in the decimal form on OCD/Serial Debug Interface.
void trace_u8 (U8 val)
Fonction used to display a byte value in the decimal form on OCD/Serial Debug Interface.
void trace_hex (U8 val)
Fonction used to display a byte value in the hex form on OCD/Serial Debug Interface.
void trace (const U8 *str)
Fonction used for send a texte on OCD/Serial Debug Interface.
void trace_hex16 (U16 val)
void trace_hex32 (U32 val)
void trace_nl ()
Variables
U8 _MEM_TYPE_SLOW_ g_trace_en = TRUE
Detailed Description
This file holds definitions to help software designers in debugging their applications.
Compiler: IAR EWAVR and GNU GCC for AVR
Supported devices: AT90USB1287, AT90USB1286, AT90USB647, AT90USB646
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file debug.c.
Define Documentation
#define _TRACE_ (DISABLE)
Definition at line 46 of file debug.c.
Function Documentation
void trace_u32 (U32 val)
Fonction used to display a byte value in the decimal form (16 bits) on OCD/Serial Debug Interface.
Parameters:
val,: value of byte
Definition at line 72 of file debug.c.
Referenced by nf_scan().
{
   if( FALSE==g_trace_en ) return;
   printf("%lu",val);
}
void trace_u16 (U16 val)
Fonction used to display a 16-bit value in the decimal form on OCD/Serial Debug Interface.
Parameters:
val,: value of byte
Definition at line 82 of file debug.c.
Referenced by nf_check_fbb().
{
   if( FALSE==g_trace_en ) return;
   printf("%u",val);
}
void trace_u8 (U8 val)
Fonction used to display a byte value in the decimal form on OCD/Serial Debug Interface.
Parameters:
val,: value of byte
Definition at line 92 of file debug.c.
Referenced by nf_swap(), and nf_translate().
{
   if( FALSE==g_trace_en ) return;
   printf("%u",val);
}
void trace_hex (U8 val)
Fonction used to display a byte value in the hex form on OCD/Serial Debug Interface.
Parameters:
val,: value of byte
Definition at line 102 of file debug.c.
Referenced by nf_check_fbb(), nf_rebuild(), nf_scan(), and nf_write_lut().
{
   if( FALSE==g_trace_en ) return;
   printf("0x%02X",val);
}
void trace (const U8 * str)
Fonction used for send a texte on OCD/Serial Debug Interface.
Parameters:
str,: texte to send (max. size = 256)
Definition at line 114 of file debug.c.
Referenced by main(), nf_cache_fbb_flush(), nf_cache_fbb_refill(), nf_cache_lut_flush(), nf_cache_lut_refill(), nf_check_fbb(), nf_copy_tail(), nf_dfc_write_stop(), nf_erase_old_blocks(), nf_read_10(), nf_rebuild(), nf_scan(), nf_swap(), nf_translate(), nf_write_10(), nf_write_lut(), and trace_nl().
{
   if( FALSE==g_trace_en ) return;
   printf((const char*)str);
}
void trace_hex16 (U16 val)
Definition at line 121 of file debug.c.
Referenced by nf_cache_fbb_flush(), nf_cache_fbb_refill(), nf_cache_lut_flush(), nf_cache_lut_refill(), nf_check_fbb(), nf_erase_old_blocks(), nf_read_10(), nf_rebuild(), nf_scan(), nf_write_10(), and nf_write_lut().
{
   printf("0x%04X",val);
}
void trace_hex32 (U32 val)
Definition at line 126 of file debug.c.
Referenced by nf_cache_lut_refill(), nf_copy_tail(), nf_dfc_write_stop(), nf_read_10(), nf_rebuild(), nf_swap(), nf_translate(), and nf_write_10().
{
   printf("0x%08lX",val);
}
void trace_nl (void)
Definition at line 131 of file debug.c.
Referenced by main(), nf_cache_fbb_flush(), nf_cache_fbb_refill(), nf_cache_lut_flush(), nf_cache_lut_refill(), nf_check_fbb(), nf_copy_tail(), nf_dfc_write_stop(), nf_erase_old_blocks(), nf_read_10(), nf_rebuild(), nf_scan(), nf_swap(), nf_translate(), nf_write_10(), and nf_write_lut().
{
   trace("\n\r");
}
Variable Documentation
U8 _MEM_TYPE_SLOW_ g_trace_en = TRUE
Definition at line 64 of file debug.c.
Referenced by trace(), trace_hex(), trace_u16(), trace_u32(), and trace_u8().