ATMEL: main.c File Reference
main.c File Reference
#include "config.h"
#include "modules/scheduler/scheduler.h"
#include "lib_mcu/wdt/wdt_drv.h"
#include "lib_mcu/power/power_drv.h"
#include "lib_mem/nf/nf_mngt.h"
#include "lib_mcu/uart/uart_lib.h"
#include "lib_mcu/debug.h"
Defines
#define _TRACE_ (DISABLE)
Functions
int main (void)
Procedure to speed up the startup code
This one increment the CPU clock before RAM initialisation
char __low_level_init ()
Detailed Description
Main for USB application.
Compiler: IAR EWAVR and GNU GCC for AVR
Supported devices: AT90USB1287, AT90USB1286, AT90USB647, AT90USB646
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file main.c.
Define Documentation
#define _TRACE_ (DISABLE)
Definition at line 144 of file main.c.
Function Documentation
int main (void)
Definition at line 151 of file main.c.
References Avr_ms_board_init, Clear_prescaler, Hwb_button_init, Joy_init, Leds_init, nf_init(), NF_N_DEVICES, nf_test_unit_ready(), nfc_check_type(), nfc_detect(), scheduler(), trace(), trace_nl(), uart_getchar(), uart_init(), uart_putchar, and wdtdrv_disable().
{
   U8 nb_device;
   wdtdrv_disable();
   Clear_prescaler();
   uart_init();
#ifdef __GNUC__
   fdevopen((int (*)(char, FILE*))(uart_putchar),(int (*)(FILE*))uart_getchar); //for printf redirection used in TRACE
#endif
   trace("\x0C-----------Start\n\r");
   trace_nl();
   // STK525 init
   Leds_init();
   Joy_init();
   Hwb_button_init();
   // Mass Storage Extension board init
   Avr_ms_board_init();
   // NAND Flash Initialization
#if (NF_AUTO_DETECT_2KB == FALSE) && (NF_AUTO_DETECT_512B == FALSE)
   nb_device = nfc_check_type(NF_N_DEVICES);
   while( NF_N_DEVICES != nb_device );
#else
   nfc_detect();
#endif
   nf_init();
   nf_test_unit_ready();
   scheduler();
   return 0;
}
char __low_level_init ()
Definition at line 199 of file main.c.
References Clear_prescaler.
{
  Clear_prescaler();
  return 1;
}