ATMEL: mmc_sd_mem.c File Reference
mmc_sd_mem.c File Reference
#include "config.h"
#include "conf_sdmmc.h"
#include "mmc_sd_mem.h"
#include "mmc_sd.h"
Functions
void mmc_sd_mem_init (void)
Ctrl_status mmc_sd_test_unit_ready (void)
Ctrl_status mmc_sd_read_capacity (U32 _MEM_TYPE_SLOW_ *u32_nb_sector)
Bool mmc_sd_wr_protect (void)
Bool mmc_sd_removal (void)
Ctrl_status mmc_sd_read_10 (U32 addr, U16 nb_sector)
Ctrl_status mmc_sd_write_10 (U32 addr, U16 nb_sector)
This fonction initialise the memory for a write operation.
Ctrl_status mmc_ram_2_mmc (U32 addr, U8 *ram)
This fonction initialise the memory for a write operation from ram buffer to MMC/SD (1 sector).
Ctrl_status mmc_mmc_2_ram (U32 addr, U8 *ram)
This fonction read 1 sector from MMC/SD to ram buffer.
Variables
xdata U32 MMC_SD_DISK_SIZE
volatile U32 mmc_sd_last_address
bit mmc_sd_init_done
U8 mmc_sd_presence_status = 0
bit mmc_sd_init_done
Detailed Description
This file contains the interface routines of Data Flash memory.
Compiler: IAR EWAVR and GNU GCC for AVR
Supported devices: AT90USB1287, AT90USB1286, AT90USB647, AT90USB646
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file mmc_sd_mem.c.
Function Documentation
void mmc_sd_mem_init (void)
This function initializes the hw/sw ressources required to drive the MMC_SD.
Warning:
Code:?? bytes (function code length)
Parameters:
none
Returns:
none
/
Definition at line 82 of file mmc_sd_mem.c.
Referenced by mmc_mmc_2_ram(), mmc_ram_2_mmc(), mmc_sd_read_10(), mmc_sd_read_capacity(), mmc_sd_test_unit_ready(), and mmc_sd_write_10().
{
   mmc_sd_init();        // Init the SPI bus and the MMC/SD card
}
Ctrl_status mmc_sd_test_unit_ready (void)
This function tests the state of the MMC_SD memory and sends it to the Host. For a PC, this device is seen as a removable media Before indicating any modification of the status of the media (GOOD->NO_PRESENT or vice-versa), the function must return the BUSY data to make the PC accepting the change
Warning:
Code:?? bytes (function code length)
Parameters:
none
Returns:
Ctrl_status Media is ready -> CTRL_GOOD Media not present -> CTRL_NO_PRESENT Media has changed -> CTRL_BUSY /
Definition at line 103 of file mmc_sd_mem.c.
{
  Sdmmc_access_signal_on();
   if (mmc_sd_init_done == FALSE)
   {
      mmc_sd_mem_init();
   }
  switch (mmc_sd_presence_status)
  {
    case MMCSD_REMOVED:
      mmc_sd_init_done = FALSE;
      if (OK == mmc_sd_mem_check())
      {
        mmc_sd_presence_status = MMCSD_INSERTED;
        Sdmmc_access_signal_off();
        return CTRL_BUSY;
      }
      Sdmmc_access_signal_off();
      return CTRL_NO_PRESENT;
    case MMCSD_INSERTED:
      if (OK != mmc_sd_mem_check())
      {
        mmc_sd_presence_status = MMCSD_REMOVING;
        mmc_sd_init_done = FALSE;
        Sdmmc_access_signal_off();
        return CTRL_BUSY;
      }
      Sdmmc_access_signal_off();
      return CTRL_GOOD;
    case MMCSD_REMOVING:
      mmc_sd_presence_status = MMCSD_REMOVED;
      Sdmmc_access_signal_off();
      return CTRL_NO_PRESENT;
    default:
      mmc_sd_presence_status = MMCSD_REMOVED;
      Sdmmc_access_signal_off();
      return CTRL_BUSY;
  }
  Sdmmc_access_signal_off();
  return CTRL_BUSY;
/*
  if (OK==mmc_sd_mem_check())
  {
    if (mmc_sd_status_changed == FALSE)
    {
      mmc_sd_status_changed = TRUE;
      return CTRL_BUSY;     // BUSY token must be returned to indicate a status change !
    }
    else
      return CTRL_GOOD;     // the 2nd time the host will ask for unit_ready, we can answer GOOD if we have returned BUSY first !
  }
  else
  {
    if (mmc_sd_status_changed == TRUE)
    {
      mmc_sd_status_changed = FALSE;
      return CTRL_BUSY;     // BUSY token must be returned to indicate a status change !
    }
    else
      return CTRL_NO_PRESENT;
  }
*/
}
Ctrl_status mmc_sd_read_capacity (U32 _MEM_TYPE_SLOW_ * u32_nb_sector)
This function gives the address of the last valid sector.
Warning:
Code:?? bytes (function code length)
Parameters:
*u32_nb_sector number of sector (sector = 512B). OUT
Returns:
Ctrl_status Media ready -> CTRL_GOOD Media not present -> CTRL_NO_PRESENT /
Definition at line 183 of file mmc_sd_mem.c.
{
//   mmc_sd_check_presence();   // ommited because creates interferences with "mmc_sd_test_unit_ready()" function
   Sdmmc_access_signal_on();
   if (mmc_sd_init_done == FALSE)
   {
      mmc_sd_mem_init();
   }
   if (mmc_sd_init_done == TRUE)
   {
     *u32_nb_sector = mmc_sd_last_block_address;
     Sdmmc_access_signal_off();
     return CTRL_GOOD;
   }
   else
   {
     Sdmmc_access_signal_off();
     return CTRL_NO_PRESENT;
   }
}
Bool mmc_sd_wr_protect (void)
This function returns the write protected status of the memory.
Only used by memory removal with a HARDWARE SPECIFIC write protected detection !!! The customer must unplug the memory to change this write protected status, which cannot be for a MMC_SD.
Warning:
Code:?? bytes (function code length)
Returns:
FALSE -> the memory is not write-protected (always) /
Definition at line 216 of file mmc_sd_mem.c.
{
   return FALSE;
}
Bool mmc_sd_removal (void)
This function tells if the memory has been removed or not.
Parameters:
none
Warning:
Code:?? bytes (function code length)
Returns:
FALSE -> The memory isn't removed /
Definition at line 231 of file mmc_sd_mem.c.
{
  return FALSE;
//  return ((OK == mmc_sd_check_presence()) ? FALSE : TRUE);
}
Ctrl_status mmc_sd_read_10 (U32 addr, U16 nb_sector)
This function performs a read operation of n sectors from a given address on. (sector = 512B)
DATA FLOW is: MMC_SD => USB
Warning:
Code:?? bytes (function code length)
Parameters:
addr Sector address to start the read from
nb_sector Number of sectors to transfer
Returns:
Ctrl_status It is ready -> CTRL_GOOD A error occur -> CTRL_FAIL
Definition at line 257 of file mmc_sd_mem.c.
{
bit status;
   if (mmc_sd_init_done == FALSE)
   {
      mmc_sd_mem_init();
   }
   if (mmc_sd_init_done == TRUE)
   {
     Sdmmc_access_signal_on();
     mmc_sd_read_open(addr);
     status = mmc_sd_read_sector(nb_sector);
     mmc_sd_read_close();
     Sdmmc_access_signal_off();
     if (status == OK)
        return CTRL_GOOD;
     else
        return CTRL_NO_PRESENT;
   }
   else
     return CTRL_NO_PRESENT;
}
Ctrl_status mmc_sd_write_10 (U32 addr, U16 nb_sector)
This fonction initialise the memory for a write operation.
DATA FLOW is: USB => MMC_SD
(sector = 512B)
Parameters:
addr Sector address to start write
nb_sector Number of sectors to transfer
Returns:
Ctrl_status It is ready -> CTRL_GOOD A error occur -> CTRL_FAIL
Definition at line 294 of file mmc_sd_mem.c.
{
  bit status;
   if (mmc_sd_init_done == FALSE)
   {
      mmc_sd_mem_init();
   }
   if (mmc_sd_init_done == TRUE)
   {
     Sdmmc_access_signal_on();
     mmc_sd_write_open(addr);
     status = mmc_sd_write_sector(nb_sector);
     mmc_sd_write_close();
     Sdmmc_access_signal_off();
     if (status == OK)
       return CTRL_GOOD;
     else
       return CTRL_NO_PRESENT;
   }
   else
     return CTRL_NO_PRESENT;
}
Ctrl_status mmc_ram_2_mmc (U32 addr, U8 * ram)
This fonction initialise the memory for a write operation from ram buffer to MMC/SD (1 sector).
DATA FLOW is: RAM => MMC
(sector = 512B)
Parameters:
addr Sector address to write
ram Ram buffer pointer
Returns:
Ctrl_status It is ready -> CTRL_GOOD A error occur -> CTRL_FAIL
Definition at line 333 of file mmc_sd_mem.c.
{
#if (MMC_SD_RAM == ENABLE)
   Sdmmc_access_signal_on();
   mmc_sd_check_presence();
   if (mmc_sd_init_done == FALSE)
   {
      mmc_sd_mem_init();
   }
   if (mmc_sd_init_done == TRUE)
   {
     mmc_sd_write_open(addr);
     if (KO == mmc_sd_write_sector_from_ram(ram))
     {
       mmc_sd_write_close();
       Sdmmc_access_signal_off();
       return CTRL_NO_PRESENT;
     }
     mmc_sd_write_close();
     Sdmmc_access_signal_off();
     return CTRL_GOOD;
   }
   Sdmmc_access_signal_off();
#endif   // (MMC_SD_RAM == ENABLE)
     return CTRL_NO_PRESENT;
}
Ctrl_status mmc_mmc_2_ram (U32 addr, U8 * ram)
This fonction read 1 sector from MMC/SD to ram buffer.
DATA FLOW is: MMC => RAM
(sector = 512B)
Parameters:
addr Sector address to read
ram Ram buffer pointer
Returns:
Ctrl_status It is ready -> CTRL_GOOD A error occur -> CTRL_FAIL
Definition at line 373 of file mmc_sd_mem.c.
{
#if (MMC_SD_RAM == ENABLE)
   Sdmmc_access_signal_on();
   mmc_sd_check_presence();
   if (mmc_sd_init_done == FALSE)
   {
      mmc_sd_mem_init();
   }
   if (mmc_sd_init_done == TRUE)
   {
     mmc_sd_read_open(addr);
     if (KO == mmc_sd_read_sector_to_ram(ram))
     {
       mmc_sd_write_close();
       Sdmmc_access_signal_off();
       return CTRL_NO_PRESENT;
     }
     mmc_sd_read_close();
     Sdmmc_access_signal_off();
     return CTRL_GOOD;
   }
   Sdmmc_access_signal_off();
#endif   // (MMC_SD_RAM == ENABLE)
   return CTRL_NO_PRESENT;
}
Variable Documentation
xdata U32 MMC_SD_DISK_SIZE
volatile U32 mmc_sd_last_address
bit mmc_sd_init_done
Definition at line 57 of file mmc_sd.c.
U8 mmc_sd_presence_status = 0
Definition at line 65 of file mmc_sd_mem.c.
Referenced by mmc_sd_test_unit_ready().
bit mmc_sd_init_done
Definition at line 57 of file mmc_sd.c.