ATMEL: host_template_task.c File Reference
host_template_task.c File Reference
#include "config.h"
#include "conf_usb.h"
#include "host_template_task.h"
#include "modules/usb/host_chap9/usb_host_task.h"
#include "modules/usb/host_chap9/usb_host_enum.h"
#include "lib_mcu/usb/usb_drv.h"
#include "lib_mcu/uart/uart_lib.h"
Functions
void host_template_task_init (void)
void host_template_task (void)
void call_back_template_1 (U8 status, U16 nb_byte)
void call_back_template_2 (U8 status, U16 nb_byte)
Variables
U8 tab [64]
U8 busy = FALSE
U8 pipe_out
U8 pipe_in
U8 pipe_interrupt_in
Detailed Description
This file manages the high level USB Host application.
Compiler: IAR EWAVR and GNU GCC for AVR
Supported devices: AT90USB1287, AT90USB1286, AT90USB647, AT90USB646
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file host_template_task.c.
Function Documentation
void host_template_task_init (void)
This function initializes the high level host application Here initialize specific hardware ressources requirements.
Parameters:
none
Returns:
none
Definition at line 74 of file host_template_task.c.
References Hwb_button_init, i, Joy_init, Leds_init, and tab.
{
   U8 i;
   for(i=0;i<sizeof(tab);i++)
   {
      tab[i]=i;
   }
   Leds_init();
   Joy_init();
   Hwb_button_init();
}
void host_template_task (void)
High level host application task entry point Put here the code of your host application. The sample code just sends and receives 64bytes from IN and OUT pipes
Parameters:
none
Returns:
none
Definition at line 96 of file host_template_task.c.
References busy, call_back_template_1(), FALSE, Get_class, Get_ep_addr, Get_nb_supported_interface, Get_protocol, Get_subclass, Host_ack_in_received, Host_continuous_in_mode, host_get_data(), host_get_hwd_pipe_nb(), Host_read_byte, Host_request_resume, Host_request_suspend, Host_select_pipe, host_send_data(), host_send_data_interrupt(), Host_send_in, Host_unfreeze_pipe, i, Is_btn_middle, Is_device_disconnection_event, Is_ep_addr_in, Is_host_in_received, Is_host_ready, Is_host_stall, Is_host_suspended, Is_hwb, Is_new_device_connection_event, pipe_in, pipe_interrupt_in, pipe_out, tab, and TRUE.
{
   #if (USB_HOST_PIPE_INTERRUPT_TRANSFER == DISABLE)
   U8 sta;
   #endif
   U16 *ptr_nb;
   U16 nb;
   U8 i;
   ptr_nb=&nb;
   // First check the host controller is in full operating mode with the B device attached
   // and enumerated
   if(Is_host_ready())
   {
      //Put here the code to do in host mode
      // New device connection (executed  only one time after device connection)
      if(Is_new_device_connection_event())
      {
         for(i=0;i<Get_nb_supported_interface();i++)
         {
            // First interface with two bulk IN/OUT pipes
            if(Get_class(i)==0x00 && Get_subclass(i)==0x00 && Get_protocol(i)==0x00)
            {
               //Get correct physical pipes associated to IN/OUT Endpoints
               if(Is_ep_addr_in(Get_ep_addr(i,0)))
               {  //Yes associate it to the IN pipe
                  pipe_in=host_get_hwd_pipe_nb(Get_ep_addr(i,0));
                  pipe_out=host_get_hwd_pipe_nb(Get_ep_addr(i,1));
               }
               else
               {  //No, invert...
                  pipe_in=host_get_hwd_pipe_nb(Get_ep_addr(i,1));
                  pipe_out=host_get_hwd_pipe_nb(Get_ep_addr(i,0));
               }
            }
            // Seconf interface with interrupt IN pipe
            if(Get_class(i)==0x00 && Get_subclass(i)==0x55 && Get_protocol(i)==0xAA)
            {
               pipe_interrupt_in=host_get_hwd_pipe_nb(Get_ep_addr(i,0));
               Host_select_pipe(pipe_interrupt_in);
               Host_continuous_in_mode();
               Host_unfreeze_pipe();
            }
         }
      }
     // Firt interface (bulk IN/OUT) management
     // In polling mode
#if (USB_HOST_PIPE_INTERRUPT_TRANSFER == DISABLE)
      // The sample task sends 64 byte through pipe nb2...
      sta=host_send_data(pipe_out,64,tab);
      // And receives 64bytes from pipe nb 1...
      *ptr_nb=64;
      sta=host_get_data(pipe_in,ptr_nb,tab);
#else
      // similar applicative task under interrupt mode...
      if (busy==FALSE)
      {
         busy=TRUE;
         host_send_data_interrupt(pipe_out,64,tab,call_back_template_1);
      }
#endif
      // Second interface management (USB interrupt IN pipe)
      Host_select_pipe(pipe_interrupt_in);
      if(Is_host_in_received())
      {
         if(Is_host_stall()==FALSE)
         {
            i=Host_read_byte();
            Host_read_byte();
         }
         Host_ack_in_received(); Host_send_in();
      }
      // Here an example of an applicative request to go to USB suspend ...
      if(Is_hwb())
      {
         Host_request_suspend();
      }
   }
   // Here an applicative example of resume request...
   if(Is_host_suspended() && Is_btn_middle())
   {
      Host_request_resume();
   }
   //Device disconnection...
   if(Is_device_disconnection_event())
   {
      //Put here code to be executed upon device disconnection...
   }
}
void call_back_template_1 (U8 status, U16 nb_byte)
Definition at line 195 of file host_template_task.c.
Referenced by host_template_task().
{
   if (status==PIPE_GOOD)
   {
      host_get_data_interrupt(pipe_in,64,tab,call_back_template_2);
   }
}
void call_back_template_2 (U8 status, U16 nb_byte)
Definition at line 204 of file host_template_task.c.
Referenced by call_back_template_1().
{
   if (status==PIPE_GOOD)
   {
      busy=FALSE;
   }
}
Variable Documentation
U8 tab[64]
Definition at line 58 of file host_template_task.c.
Referenced by call_back_template_1(), host_template_task(), and host_template_task_init().
U8 busy = FALSE
Definition at line 59 of file host_template_task.c.
Referenced by call_back_template_2(), and host_template_task().
U8 pipe_out
Definition at line 60 of file host_template_task.c.
Referenced by host_template_task().
U8 pipe_in
Definition at line 61 of file host_template_task.c.
Referenced by call_back_template_1(), and host_template_task().
U8 pipe_interrupt_in
Definition at line 62 of file host_template_task.c.
Referenced by host_template_task().